version: '3'
services:
  workspace:
    #    image: neibrs/drocker
    build:
      context: ./docker
    container_name: workspace
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.host.internal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./drupal/web:/var/www/localhost/htdocs
    ports:
      - 83:80
    ### Drupal ######################################################
  drupal:
    container_name: alpine_drupal
    build:
      context: ./drupal
#      args:
#        - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
#        - NPM_REGISTRY=${WORKSPACE_NPM_REGISTRY}
#        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
#        - YARN_VERSION=${WORKSPACE_YARN_VERSION}
