version: '3'
services:
  workspace:
    image: neibrs/drocker:dev
    container_name: workspace
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.host.internal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./drupal/web:/var/www/localhost/htdocs
    ports:
      - 80:80
  drupal:
    image: neibrs/drocker:drupal
    container_name: drupal
